config/routes.rb
Rails.application.routes.draw do
  root "hobbies#index"
  devise_for :users
  resources :hobbies 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hobby.rb
class Hobby < ApplicationRecord
  belongs_to :user 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :hobbies 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user! 

  protected 

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end 
end

app/controllers/hobbies_controller.rb
class HobbiesController < ApplicationController
  before_action :set_hobby, only: [:show, :edit, :update, :destroy]


  def index
    @hobbies = current_user.hobbies 
  end

  def show

  end

  def new
    @hobby = current_user.hobbies.new 
  end

  def create
    @hobby = current_user.hobbies.new(hobby_params)
    if @hobby.save 
      flash[:success] = "Hobby Created"
      redirect_to hobbies_path  
    else 
      flash[:error] = "Error #{@hobby.errors.full_messages.join("\n")}"
      render :new 
    end 

    
  end 

  def edit

  end

  def update 
    if @hobby.update(hobby_params)
      redirect_to @hobby 
    else 
      render :edit
    end 
  end 

  def destroy
    @hobby.destroy 
    redirect_to hobbies_path 
  end 

  private 

  def hobby_params  
    params.require(:hobby).permit(:name, :body)
  end 
  
  def set_hobby
    @hobby = current_user.hobbies.find(params[:id])
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hobbies_helper.rb
module HobbiesHelper
end

app/views/hobbies/edit.html.erb
<h1>Edit Hobby</h1>
<%= form_with(model: @hobby, local: true) do |h| %>
  <div class="field">
    <%= h.label :name %>
    <%= h.text_field :name, required: true, placeholder: "Name" %>
  </div>
  <div class="field">
    <%= h.label :body %>
    <%= h.text_area :body %>
  </div>
  <%= h.submit class: "waves-effect waves-light btn teal accent-3"%>
<% end %>

app/views/hobbies/index.html.erb
<h2>My Hobbies</h2> 
<%= link_to 'Add Hobby', new_hobby_path %>
<hr />
<% @hobbies.each do |h| %>
  <div class="row">
    <div class="col s12 m6">
      <div class="card blue-grey lighten-2">
        <div class="card-content white-text">
          <span class="card-title"><%= h.name %></span>
          <hr />
          <p> <%= h.body %> </p>
        </div>
        <div class="card-action teal accent-3">
          <%= link_to "Edit", edit_hobby_path(h), {:style=>'color:#FFFFFF;'} %>
          <%= link_to "Show", hobby_path(h), {:style=>'color:#FFFFFF;'}%>
          <%= link_to "Delete", hobby_path(h), :style=>'color:#FFFFFF;', method: :delete %>
        </div>
      </div>
    </div>
  </div>
   <% end %> 

app/views/hobbies/new.html.erb
<h1>Add Hobby</h1>
<%= form_with(model: @hobby, local: true) do |h| %>
  <div class="field">
    <%= h.label :name %>
    <%= h.text_field :name, required: true, placeholder: "Name" %>
  </div>
  <div class="field">
    <%= h.label :body %>
    <%= h.text_area :body %>
  </div>
  <%= h.submit class: "waves-effect waves-light btn teal accent-3"%>
<% end %>

app/views/layouts/_navbar.html.erb
  <nav class="teal accent-3">
    <div class="nav-wrapper">
      <%= link_to "Hobbies", hobbies_path, class: "brand-logo" %>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <% if current_user %>
          <li>
            <%= link_to 'Hobbies', hobbies_path %>
          </li>
          <li>
            <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
          </li>
        <% else %>
          <li>
            <%= link_to "Register", new_user_registration_path %>
          </li>
          <li>
            <%= link_to "Log In", new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render "layouts/navbar" %>
    <div class="container">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>">
            <%= value %> 
          </div>
        <% end %>
    <%= yield %>
    </div>
  </body>
</html>